# Generated by Django 6.0.3 on 2026-04-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ID', models.CharField(max_length=7, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_type', models.IntegerField(choices=[(0, 'Hourly'), (1, 'Salaried')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_module', models.IntegerField(choices=[(0, 'Induction Training'), (1, '5 S Workshop'), (2, 'FPS Training'), (3, '5 Whys Training'), (4, 'Waste Elimination'), (5, 'Kaizen Training'), (6, 'Metal Finish Training'), (7, 'SPII Training'), (8, 'Leadership Training'), (9, 'SPC CHarts Training'), (10, 'PMHV & Safety Training')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_description', models.CharField(blank=True, max_length=150)),
                ('trainer_company_ID', models.CharField(max_length=7)),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_surname', models.CharField(max_length=50)),
                ('hours_of_training', models.IntegerField()),
                ('captured_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_trainings', to='database_models.contractor')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='database_models.employee')),
            ],
        ),
    ]
