# Generated by Django 6.0.3 on 2026-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0002_alter_trainingmodule_captured_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='course_description',
        ),
    ]
